// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bborzcdfxrangvewmpfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib3J6Y2RmeHJhbmd2ZXdtcGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzA1NjEsImV4cCI6MjA2MDQ0NjU2MX0.XOHKGW4PHqQCtbr1YAptZjTohf_CCkEyPA60nnIVPl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);